# -*- coding: utf-8 -*-
"""「Untitled0_ipynbasa本.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/h124577999-art/dsd/blob/main/%E3%80%8CUntitled0_ipynbasa%E6%9C%AC.ipynb
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.patches import Rectangle, Circle
import base64
import tempfile
import os

# --- 網頁配置 ---
st.set_page_config(page_title="戰術防禦模擬系統", layout="wide")
st.title("🛡️ 戰術防禦互動模擬：SUT vs 傳統防禦")

# --- 側邊欄：參數設定 ---
st.sidebar.header("🕹️ 戰術參數調校")
e_count = st.sidebar.slider("敵軍波次數量", 5, 25, 12)
e_speed = st.sidebar.slider("敵軍進攻速度", 0.5, 2.0, 1.15)
sut_hit_p = st.sidebar.slider("SUT 基礎攔截率", 0.5, 1.0, 0.88)
trad_hit_p = st.sidebar.slider("傳統組基礎攔截率", 0.1, 0.8, 0.42)

# --- 1. 核心模擬引擎 (100次運算) ---
def run_realistic_sim(mode, e_num, e_spd, hit_p_val):
    np.random.seed(42)
    results = []
    d_lim = 18 if mode == "sut" else 12
    for _ in range(100):
        e_pos = np.random.rand(e_num, 2) * 45 + 5
        e_targets = np.array([110, 60]) + np.random.uniform(-30, 30, (e_num, 2))
        health, deaths = 100.0, 0
        if mode == "sut":
            units = [{'pos': np.array([60.0, 45.0]), 'active': True}, {'pos': np.array([60.0, 75.0]), 'active': True}]
            risk = 0.045
        else:
            units = [{'pos': np.array(p), 'active': True} for p in [[25, 60], [95, 60], [105, 35], [105, 85]]]
            risk = 0.012
        for _ in range(160):
            if len(e_pos) == 0 or health <= 0: break
            active_e_idx = []
            for u in units:
                if not u['active']: continue
                if mode == "sut":
                    t_idx = np.argmin(np.linalg.norm(e_pos - u['pos'], axis=1))
                    u['pos'] += (e_pos[t_idx] - u['pos']) / 8.0
                for i in range(len(e_pos)):
                    if np.linalg.norm(u['pos'] - e_pos[i]) < 8 and np.random.rand() < risk:
                        u['active'] = False; deaths += 1; break
            for i in range(len(e_pos)):
                dir_v = e_targets[i] - e_pos[i]
                e_pos[i] += (dir_v / np.linalg.norm(dir_v)) * e_spd
                if np.linalg.norm(e_pos[i] - np.array([110, 60])) < 8: health -= 3.5
                is_hit = False
                for u in units:
                    if u['active'] and np.linalg.norm(u['pos'] - e_pos[i]) < d_lim:
                        if np.random.rand() < hit_p_val: is_hit = True; break
                if not is_hit: active_e_idx.append(i)
            e_pos = e_pos[active_e_idx]; e_targets = e_targets[active_e_idx]
        results.append([max(0, health), (deaths / len(units)) * 100])
    return np.array(results)

# --- 2. 啟動模擬運算與顯示 ---
if st.sidebar.button("🚀 啟動模擬"):
    # 執行運算
    data_trad = run_realistic_sim("trad", e_count, e_speed, trad_hit_p)
    data_sut = run_realistic_sim("sut", e_count, e_speed, sut_hit_p)

    # 顯示統計圖
    st.subheader("📊 統計數據分析 (每 10 次平均值)")
    fig_stat, axs = plt.subplots(2, 2, figsize=(10, 8))
    def plot_bars(ax, raw_data, col, title, color):
        group_avgs = np.mean(raw_data[:, col].reshape(10, 10), axis=1)
        bars = ax.bar(range(1, 11), group_avgs, color=color, alpha=0.7, edgecolor='black')
        for b in bars:
            ax.text(b.get_x()+b.get_width()/2, b.get_height()+1, f'{b.get_height():.1f}', ha='center', fontweight='bold')
        ax.set_title(title); ax.set_ylim(0, 115); ax.set_xticks(range(1, 11))

    plot_bars(axs[0, 0], data_trad, 0, "Trad Health", "red")
    plot_bars(axs[0, 1], data_sut, 0, "SUT Health", "blue")
    plot_bars(axs[1, 0], data_trad, 1, "Trad Casualty", "orange")
    plot_bars(axs[1, 1], data_sut, 1, "SUT Casualty", "cyan")
    st.pyplot(fig_stat)

    # --- 3. 修正後的動畫生成區塊 ---
    st.subheader("🎬 實時接戰演示 (無外框數值)")
    fig_ani, (v1, v2) = plt.subplots(1, 2, figsize=(12, 6))
    def setup_map(ax, title):
        ax.set_xlim(0, 140); ax.set_ylim(0, 120); ax.set_title(title)
        ax.add_patch(Circle((110, 60), 8, color='purple', alpha=0.1))
        ax.set_xticks([]); ax.set_yticks([]) # 確保移除外框數值

    setup_map(v1, "Traditional Defense"); setup_map(v2, "SUT Defense")
    se1 = v1.scatter([], [], c='red', marker='x'); sg1 = v1.scatter([], [], c='blue', s=80)
    se2 = v2.scatter([], [], c='red', marker='x'); sg2 = v2.scatter([], [], c='blue', marker='^', s=100)

    # 動畫用初始化
    ave1 = np.random.rand(e_count, 2) * 45 + 5; ave2 = ave1.copy()
    avg1 = [[25, 60, True], [95, 60, True], [105, 35, True], [105, 85, True]]
    avg2 = [[60, 45, True], [60, 75, True]]

    def update(f):
        global ave1, ave2
        # (這裡簡化運算以加速網頁渲染)
        for i in range(len(ave1)): ave1[i] += (np.array([110, 60]) - ave1[i]) / 60 * e_speed
        for i in range(len(ave2)): ave2[i] += (np.array([110, 60]) - ave2[i]) / 60 * e_speed
        se1.set_offsets(ave1); sg1.set_offsets([g[:2] for g in avg1])
        se2.set_offsets(ave2); sg2.set_offsets([g[:2] for g in avg2])
        return se1, sg1, se2, sg2

    ani = FuncAnimation(fig_ani, update, frames=60, blit=True)

    # 使用臨時檔案存儲 GIF
    tmp_file = tempfile.NamedTemporaryFile(delete=False, suffix='.gif')
    ani.save(tmp_file.name, writer='pillow', fps=15)

    # 讀取並轉換為 Base64 顯示
    with open(tmp_file.name, "rb") as f:
        contents = f.read()
        data_url = base64.b64encode(contents).decode("utf-8")

    st.markdown(f'<img src="data:image/gif;base64,{data_url}" width="100%">', unsafe_allow_html=True)

    # 清理臨時檔案
    tmp_file.close()
    os.remove(tmp_file.name)